export interface SecaoModulo {
  id: string
  titulo: string
}

export interface ConfigModulo {
  titulo: string
  subtitulo: string
  duracao: string
  numCasos: number
  disponivel: boolean
  secoes: SecaoModulo[]
  anterior?: string
  seguinte?: string
}

export const MODULOS_CONFIG: Record<string, ConfigModulo> = {
  'modulo-1': {
    titulo: 'Neurociência do Sonho',
    subtitulo: 'Como o cérebro produz e usa os sonhos',
    duracao: '3–4 horas',
    numCasos: 3,
    disponivel: true,
    seguinte: 'modulo-2',
    secoes: [
      { id: 'introdução', titulo: 'Introdução' },
      { id: 'arquitectura-do-sono', titulo: 'Arquitectura do Sono' },
      { id: 'substrato-neurológico', titulo: 'Substrato Neurológico' },
      { id: 'teorias-funcionais', titulo: 'Teorias Funcionais' },
      { id: 'fronteiras-psicológicas', titulo: 'Fronteiras Psicológicas' },
      { id: 'diário-de-sonhos', titulo: 'Diário de Sonhos' },
      { id: 'exercícios', titulo: 'Exercícios' },
      { id: 'questionário', titulo: 'Questionário' },
      { id: 'síntese', titulo: 'Síntese' },
    ],
  },
  'modulo-2': {
    titulo: 'A Via Régia — Freud e a Psicanálise do Sonho',
    subtitulo: 'O sonho como via régia ao inconsciente',
    duracao: '3 horas',
    numCasos: 4,
    disponivel: false,
    anterior: 'modulo-1',
    seguinte: 'modulo-3',
    secoes: [
      { id: 'introdução', titulo: 'Introdução' },
      { id: 'revolução-de-1900', titulo: 'A Revolução de 1900' },
      { id: 'conteúdo-manifesto-latente', titulo: 'Conteúdo Manifesto e Latente' },
      { id: 'trabalho-do-sonho', titulo: 'O Trabalho do Sonho' },
      { id: 'realização-de-desejo', titulo: 'Realização de Desejo' },
      { id: 'associação-livre', titulo: 'Associação Livre na Prática' },
      { id: 'limites-e-criticas', titulo: 'Limites e Críticas' },
      { id: 'exercícios', titulo: 'Exercícios' },
      { id: 'síntese', titulo: 'Síntese' },
    ],
  },
  'modulo-3': {
    titulo: 'A Alma e o Mito — Carl Jung',
    subtitulo: 'Arquétipos, Sombra e individuação',
    duracao: '4–5 horas',
    numCasos: 6,
    disponivel: true,
    anterior: 'modulo-2',
    seguinte: 'modulo-4',
    secoes: [
      { id: 'introdução', titulo: 'Introdução' },
      { id: 'inconsciente-colectivo', titulo: 'Inconsciente Colectivo' },
      { id: 'arquétipos-principais', titulo: 'Arquétipos Principais' },
      { id: 'função-compensatória', titulo: 'Função Compensatória' },
      { id: 'amplificação', titulo: 'Amplificação' },
      { id: 'séries-de-sonhos', titulo: 'Séries de Sonhos' },
      { id: 'imaginação-activa', titulo: 'Imaginação Activa' },
      { id: 'exercícios', titulo: 'Exercícios' },
      { id: 'questionário', titulo: 'Questionário' },
      { id: 'síntese', titulo: 'Síntese' },
    ],
  },
  'modulo-4': {
    titulo: 'Ficar com a Imagem — James Hillman',
    subtitulo: 'Psicologia Arquetípica e o sonho como imagem viva',
    duracao: '3–4 horas',
    numCasos: 4,
    disponivel: false,
    anterior: 'modulo-3',
    seguinte: 'modulo-5',
    secoes: [
      { id: 'introdução', titulo: 'Introdução' },
      { id: 'revolução-arquetipal', titulo: 'A Revolução Arquetipal' },
      { id: 'mundus-imaginalis', titulo: 'Mundus Imaginalis' },
      { id: 'patologizar', titulo: 'Patologizar' },
      { id: 'politeismo-psiquico', titulo: 'Politeísmo Psíquico' },
      { id: 'submundo', titulo: 'O Submundo e Hades' },
      { id: 'entrevista-arquetipal', titulo: 'Entrevista Arquetipal' },
      { id: 'exercícios', titulo: 'Exercícios' },
      { id: 'síntese', titulo: 'Síntese' },
    ],
  },
  'modulo-5': {
    titulo: 'A Caixa de Ferramentas — Métodos Práticos',
    subtitulo: 'Delaney, Gendlin, Bosnak, Perls, Hill, Ullman e Taylor',
    duracao: '4–5 horas',
    numCasos: 8,
    disponivel: false,
    anterior: 'modulo-4',
    seguinte: 'modulo-6',
    secoes: [
      { id: 'introdução', titulo: 'Introdução' },
      { id: 'guia-de-decisão', titulo: 'Guia de Decisão Terapêutica' },
      { id: 'delaney', titulo: 'Delaney — Dream Interview' },
      { id: 'gendlin', titulo: 'Gendlin — Focusing' },
      { id: 'bosnak', titulo: 'Bosnak — Embodied Dreaming' },
      { id: 'perls', titulo: 'Perls — Gestalt' },
      { id: 'hill', titulo: 'Hill — Cognitivo-Experiencial' },
      { id: 'ullman-taylor', titulo: 'Ullman e Taylor — Grupo' },
      { id: 'supervisão', titulo: 'Supervisão com Material Onírico' },
      { id: 'exercícios', titulo: 'Exercícios' },
      { id: 'síntese', titulo: 'Síntese' },
    ],
  },
  'modulo-6': {
    titulo: 'O Despertar na Noite — Sonhos Lúcidos',
    subtitulo: 'Neurociência, técnicas e aplicações terapêuticas',
    duracao: '3–4 horas',
    numCasos: 2,
    disponivel: false,
    anterior: 'modulo-5',
    seguinte: 'modulo-7',
    secoes: [
      { id: 'introdução', titulo: 'Introdução' },
      { id: 'definição-e-prova', titulo: 'Definição e Prova Científica' },
      { id: 'técnicas-de-indução', titulo: 'Técnicas de Indução' },
      { id: 'aplicações-terapêuticas', titulo: 'Aplicações Terapêuticas' },
      { id: 'sombra-da-lucidez', titulo: 'A Sombra da Lucidez' },
      { id: 'yoga-dos-sonhos', titulo: 'Yoga dos Sonhos Tibetano' },
      { id: 'exercícios', titulo: 'Exercícios' },
      { id: 'síntese', titulo: 'Síntese' },
    ],
  },
  'modulo-7': {
    titulo: 'O Sagrado e as Tradições Globais',
    subtitulo: 'Sonhos no xamanismo, budismo, islamismo, judaísmo e tradições indígenas',
    duracao: '3 horas',
    numCasos: 3,
    disponivel: false,
    anterior: 'modulo-6',
    seguinte: 'modulo-8',
    secoes: [
      { id: 'introdução', titulo: 'Introdução' },
      { id: 'xamanismo', titulo: 'Xamanismo e Sonhos de Poder' },
      { id: 'budismo-tibetano', titulo: 'Budismo Tibetano' },
      { id: 'islamismo', titulo: 'A Tradição Islâmica' },
      { id: 'judaismo', titulo: 'A Tradição Judaica' },
      { id: 'tradições-indígenas', titulo: 'Tradições Indígenas' },
      { id: 'integração', titulo: 'Integração Contemporânea' },
      { id: 'exercícios', titulo: 'Exercícios' },
      { id: 'síntese', titulo: 'Síntese' },
    ],
  },
  'modulo-8': {
    titulo: 'A Integração na Sessão — Aplicação Terapêutica',
    subtitulo: 'Como usar sonhos no acompanhamento de bem-estar',
    duracao: '3–4 horas',
    numCasos: 5,
    disponivel: false,
    anterior: 'modulo-7',
    seguinte: 'modulo-9',
    secoes: [
      { id: 'introdução', titulo: 'Introdução' },
      { id: 'quando-introduzir', titulo: 'Quando Introduzir o Trabalho com Sonhos' },
      { id: 'ética-e-enquadramento', titulo: 'Ética e Enquadramento' },
      { id: 'resistência-do-acompanhado', titulo: 'Resistência do Acompanhado' },
      { id: 'sonho-na-transferência', titulo: 'O Sonho na Transferência' },
      { id: 'pesadelos-e-trauma', titulo: 'Pesadelos e Trauma' },
      { id: 'documentação', titulo: 'Documentação Terapêutica' },
      { id: 'exercícios', titulo: 'Exercícios' },
      { id: 'síntese', titulo: 'Síntese' },
    ],
  },
  'modulo-9': {
    titulo: 'Síntese, Identidade Profissional e Projecto Final',
    subtitulo: 'Construir a tua abordagem própria',
    duracao: '4–5 horas',
    numCasos: 4,
    disponivel: false,
    anterior: 'modulo-8',
    secoes: [
      { id: 'introdução', titulo: 'Introdução' },
      { id: 'mapa-de-influências', titulo: 'O Teu Mapa de Influências' },
      { id: 'identidade-profissional', titulo: 'Identidade Profissional' },
      { id: 'ética-deontologia', titulo: 'Ética e Deontologia' },
      { id: 'projecto-final', titulo: 'Projecto Final' },
      { id: 'síntese', titulo: 'Síntese Final' },
    ],
  },
}

export const TODOS_MODULOS = [
  { slug: 'modulo-1', numero: 'I',    titulo: 'Neurociência do Sonho',                             subtitulo: 'Como o cérebro produz e usa os sonhos',                                    duracao: '3–4 h', casos: 3, disponivel: true  },
  { slug: 'modulo-2', numero: 'II',   titulo: 'A Via Régia — Freud e a Psicanálise do Sonho',      subtitulo: 'O sonho como via régia ao inconsciente',                                   duracao: '3 h',   casos: 4, disponivel: false },
  { slug: 'modulo-3', numero: 'III',  titulo: 'A Alma e o Mito — Carl Jung',                       subtitulo: 'Arquétipos, Sombra e individuação',                                        duracao: '4–5 h', casos: 6, disponivel: true  },
  { slug: 'modulo-4', numero: 'IV',   titulo: 'Ficar com a Imagem — James Hillman',                subtitulo: 'Psicologia Arquetípica e o sonho como imagem viva',                        duracao: '3–4 h', casos: 4, disponivel: false },
  { slug: 'modulo-5', numero: 'V',    titulo: 'A Caixa de Ferramentas — Métodos Práticos',         subtitulo: 'Delaney, Gendlin, Bosnak, Perls, Hill, Ullman e Taylor',                  duracao: '4–5 h', casos: 8, disponivel: false },
  { slug: 'modulo-6', numero: 'VI',   titulo: 'O Despertar na Noite — Sonhos Lúcidos',             subtitulo: 'Neurociência, técnicas e aplicações terapêuticas',                         duracao: '3–4 h', casos: 2, disponivel: false },
  { slug: 'modulo-7', numero: 'VII',  titulo: 'O Sagrado e as Tradições Globais',                  subtitulo: 'Sonhos no xamanismo, budismo, islamismo, judaísmo e tradições indígenas',  duracao: '3 h',   casos: 3, disponivel: false },
  { slug: 'modulo-8', numero: 'VIII', titulo: 'A Integração na Sessão — Aplicação Terapêutica',    subtitulo: 'Como usar sonhos no acompanhamento de bem-estar',                          duracao: '3–4 h', casos: 5, disponivel: false },
  { slug: 'modulo-9', numero: 'IX',   titulo: 'Síntese, Identidade Profissional e Projecto Final', subtitulo: 'Construir a tua abordagem própria',                                        duracao: '4–5 h', casos: 4, disponivel: false },
]
